export enum Configuration {
  HOST = 'HOST',
  PORT = 'PORT',
  JWT_SECRET = 'JWT_SECRET',
  JWT_ALGORITHM = 'JWT_ALGORITHM',
  JWT_EXPIRATION = 'JWT_EXPIRATION',
  JWT_ISSUER = 'JWT_ISSUER',
  POSTGRESQL_USER = 'POSTGRESQL_USER',
  POSTGRESQL_PASSWORD = 'POSTGRESQL_PASSWORD',
  POSTGRESQL_DATABASE = 'POSTGRESQL_DATABASE',
}
