name: Publish

on:
  push:
    tags:
      - '*'

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - run: npm ci
      - name: Publish
        run: |
          PKG_VERSION='"'`node -p "require('./package.json').version"`'"'
          npm run build
          mv -f .github/data/.npmrc .github/data/package.json .
          node -p "fs.writeFileSync('package.json', JSON.stringify({...require('./package.json'), version: $PKG_VERSION}))"
          npm install --package-lock-only
          npm publish
        env:
          NPM_TOKEN_GITHUB: ${{ secrets.GITHUB_TOKEN }}