name: Publish

on:
  push:
    tags:
      - '*'

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'
          registry-url: 'https://npm.pkg.github.com'
      - run: npm ci
      - run: npm run build
      - name: Publish
        run: |
          mkdir types
          find dist -type f -name '*.dto.d.ts' -exec mv -i {} types \;
          cd types
          npm init -y --scope paffme
          npm version from-git
          npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}