name: Publish

on:
  push:
    tags:
      - '*'

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - run: npm ci
      - run: npm run build
      - name: Publish
        run: |
          PKG_VERSION='"'`node -p "require('./package.json').version"`'"'
          find dist -type f -name '*.dto.d.ts' -exec mv -i {} types \;
          cd types
          npm init -y --scope paffme
          node -p "fs.writeFileSync('package.json', JSON.stringify({...require('./package.json'), repository: { type: 'git', url: 'ssh://git@github.com:paffme/backend.git' }, version: $PKG_VERSION}))"
          npm publish
        env:
          NPM_TOKEN_GITHUB: ${{ secrets.GITHUB_TOKEN }}