name: CI

on:
  push:
    branches:
      - '*'

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    services:
      postgres:
        image: postgres:12.2
        env:
          POSTGRES_USER: paffme
          POSTGRES_PASSWORD: paffme
          POSTGRES_DB: paffme
        ports:
        - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
          --label postgres=postgres
      redis:
        image: redis
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 6379:6379

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install external dependencies for testing purposes
      run: sudo apt install graphicsmagick imagemagick python3
    - name: Create storage folders
      run: |
        mkdir -p ${HOME}/storage/boulders
        mkdir -p ${HOME}/storage/tmp
        mkdir ${HOME}/climbing-holds-recognition
        cp test/fixture/detection.py ${HOME}/climbing-holds-recognition
    - run: npm ci
    - run: npm run lint
    - run: npm run migrate
      env:
        POSTGRESQL_USER: paffme
        POSTGRESQL_PASSWORD: paffme
        POSTGRESQL_DATABASE: paffme
    - run: npm test
      env:
        REDIS_HOST: localhost
        REDIS_PORT: 6379
        REDIS_PREFIX: paffme
        REDIS_PASSWORD: ''
        POSTGRESQL_USER: paffme
        POSTGRESQL_PASSWORD: paffme
        POSTGRESQL_DATABASE: paffme
        JWT_SECRET: super_paffme_secret_123456789
        NODE_ENV: production
        CI: true
    - name: Upload to coveralls
      uses: coverallsapp/github-action@master
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
