name: Node.js CI

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x, 12.x]

    services:
      postgres:
        image: postgres:12
        env:
          POSTGRES_USER: paffme
          POSTGRES_PASSWORD: paffme
          POSTGRES_DB: paffme
        ports:
        - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
          --label postgres=postgres

    steps:
    - name: Enable uuid support in PostgreSQL
      run: docker exec -i $(docker ps -aqf "label=postgres") sh -c "psql -c \"CREATE EXTENSION IF NOT EXISTS 'uuid-ossp';\""
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm ci
    - run: npm run pretest
    - run: npm run migrate
    - run: npm test
      env:
        POSTGRESQL_USER: paffme
        POSTGRESQL_PASSWORD: paffme
        POSTGRESQL_DATABASE: paffme
        NODE_ENV: production
        CI: true
